# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(993, 516)
        Form.setMinimumSize(QtCore.QSize(993, 516))
        Form.setMaximumSize(QtCore.QSize(993, 516))
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setStyleSheet("QWidget#Form{\n"
"    \n"
"    \n"
"    border-image: url(:/login/images/history.jpg);\n"
"\n"
"}\n"
"")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(360, 180, 72, 15))
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(520, 470, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 470, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 60, 51, 31))
        self.pushButton_3.setStyleSheet("background-color: transparent;\n"
"font: 13pt \"华文行楷\";\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.id_label_1 = QtWidgets.QLabel(Form)
        self.id_label_1.setGeometry(QtCore.QRect(370, 130, 121, 21))
        self.id_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.id_label_1.setObjectName("id_label_1")
        self.score_label_1 = QtWidgets.QLabel(Form)
        self.score_label_1.setGeometry(QtCore.QRect(540, 130, 131, 21))
        self.score_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.score_label_1.setObjectName("score_label_1")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(310, 130, 72, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(480, 130, 72, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.card_label_1 = QtWidgets.QLabel(Form)
        self.card_label_1.setGeometry(QtCore.QRect(350, 160, 321, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.card_label_1.setFont(font)
        self.card_label_1.setStyleSheet("font: 7pt \"楷体\";")
        self.card_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.card_label_1.setObjectName("card_label_1")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(300, 160, 51, 21))
        self.label_10.setObjectName("label_10")
        self.score_label_2 = QtWidgets.QLabel(Form)
        self.score_label_2.setGeometry(QtCore.QRect(540, 220, 131, 21))
        self.score_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.score_label_2.setObjectName("score_label_2")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(300, 250, 72, 21))
        self.label_12.setObjectName("label_12")
        self.id_label_2 = QtWidgets.QLabel(Form)
        self.id_label_2.setGeometry(QtCore.QRect(370, 220, 121, 21))
        self.id_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.id_label_2.setObjectName("id_label_2")
        self.card_label_2 = QtWidgets.QLabel(Form)
        self.card_label_2.setGeometry(QtCore.QRect(350, 250, 321, 21))
        self.card_label_2.setStyleSheet("font: 7pt \"楷体\";")
        self.card_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.card_label_2.setObjectName("card_label_2")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(480, 220, 72, 21))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(310, 220, 72, 21))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(310, 310, 72, 21))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.score_label_3 = QtWidgets.QLabel(Form)
        self.score_label_3.setGeometry(QtCore.QRect(540, 310, 131, 21))
        self.score_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.score_label_3.setObjectName("score_label_3")
        self.card_label_3 = QtWidgets.QLabel(Form)
        self.card_label_3.setGeometry(QtCore.QRect(350, 340, 321, 21))
        self.card_label_3.setStyleSheet("font: 7pt \"楷体\";")
        self.card_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.card_label_3.setObjectName("card_label_3")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(480, 310, 72, 21))
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(300, 340, 72, 21))
        self.label_20.setObjectName("label_20")
        self.id_label_3 = QtWidgets.QLabel(Form)
        self.id_label_3.setGeometry(QtCore.QRect(370, 310, 121, 21))
        self.id_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.id_label_3.setObjectName("id_label_3")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(310, 400, 72, 21))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.score_label_4 = QtWidgets.QLabel(Form)
        self.score_label_4.setGeometry(QtCore.QRect(540, 400, 131, 21))
        self.score_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.score_label_4.setObjectName("score_label_4")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(480, 400, 72, 21))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(300, 430, 72, 21))
        self.label_25.setObjectName("label_25")
        self.id_label_4 = QtWidgets.QLabel(Form)
        self.id_label_4.setGeometry(QtCore.QRect(370, 400, 121, 21))
        self.id_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.id_label_4.setObjectName("id_label_4")
        self.card_label_4 = QtWidgets.QLabel(Form)
        self.card_label_4.setGeometry(QtCore.QRect(350, 430, 321, 21))
        self.card_label_4.setStyleSheet("font: 7pt \"楷体\";")
        self.card_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.card_label_4.setObjectName("card_label_4")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(690, 10, 31, 31))
        self.pushButton_4.setStyleSheet("background-color:transparent;")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.search_le = QtWidgets.QLineEdit(Form)
        self.search_le.setGeometry(QtCore.QRect(350, 60, 211, 31))
        self.search_le.setStyleSheet("background-color: transparent;\n"
"font: 10pt \"华文楷体\";")
        self.search_le.setAlignment(QtCore.Qt.AlignCenter)
        self.search_le.setClearButtonEnabled(True)
        self.search_le.setObjectName("search_le")

        self.retranslateUi(Form)
        self.pushButton_3.clicked.connect(Form.search)
        self.pushButton_2.clicked.connect(Form.uppage)
        self.pushButton.clicked.connect(Form.nextpage)
        self.pushButton_4.clicked.connect(Form.exit)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "下一页"))
        self.pushButton_2.setText(_translate("Form", "上一页"))
        self.pushButton_3.setText(_translate("Form", "搜索"))
        self.id_label_1.setText(_translate("Form", "TextLabel"))
        self.score_label_1.setText(_translate("Form", "TextLabel"))
        self.label_7.setText(_translate("Form", " 战局id："))
        self.label_8.setText(_translate("Form", "Score:"))
        self.card_label_1.setText(_translate("Form", "TextLabel"))
        self.label_10.setText(_translate("Form", " Card:"))
        self.score_label_2.setText(_translate("Form", "TextLabel"))
        self.label_12.setText(_translate("Form", " Card:"))
        self.id_label_2.setText(_translate("Form", "TextLabel"))
        self.card_label_2.setText(_translate("Form", "TextLabel"))
        self.label_15.setText(_translate("Form", "Score:"))
        self.label_16.setText(_translate("Form", " 战局id："))
        self.label_17.setText(_translate("Form", " 战局id："))
        self.score_label_3.setText(_translate("Form", "TextLabel"))
        self.card_label_3.setText(_translate("Form", "TextLabel"))
        self.label_19.setText(_translate("Form", "Score:"))
        self.label_20.setText(_translate("Form", " Card:"))
        self.id_label_3.setText(_translate("Form", "TextLabel"))
        self.label_21.setText(_translate("Form", " 战局id："))
        self.score_label_4.setText(_translate("Form", "TextLabel"))
        self.label_24.setText(_translate("Form", "Score:"))
        self.label_25.setText(_translate("Form", " Card:"))
        self.id_label_4.setText(_translate("Form", "TextLabel"))
        self.card_label_4.setText(_translate("Form", "TextLabel"))
        self.search_le.setText(_translate("Form", "请输入要查询的战局id"))
import images_rc
