# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rank.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(993, 516)
        Form.setMinimumSize(QtCore.QSize(993, 516))
        Form.setMaximumSize(QtCore.QSize(993, 516))
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(9)
        Form.setFont(font)
        Form.setStyleSheet("QWidget#Form{\n"
"\n"
"    border-image: url(:/login/images/rank.jpg);\n"
"}")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(410, 190, 151, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_1_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_1_2.setStyleSheet("font: 12pt \"楷体\";")
        self.label_1_2.setText("")
        self.label_1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_2.setObjectName("label_1_2")
        self.gridLayout.addWidget(self.label_1_2, 0, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(410, 240, 151, 41))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2_2 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_2_2.setStyleSheet("font: 12pt \"楷体\";")
        self.label_2_2.setText("")
        self.label_2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2_2.setObjectName("label_2_2")
        self.gridLayout_6.addWidget(self.label_2_2, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(410, 290, 151, 41))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_3_2.setStyleSheet("font: 12pt \"楷体\";")
        self.label_3_2.setText("")
        self.label_3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3_2.setObjectName("label_3_2")
        self.gridLayout_4.addWidget(self.label_3_2, 0, 0, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(410, 340, 151, 41))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4_2 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_4_2.setStyleSheet("font: 12pt \"楷体\";")
        self.label_4_2.setText("")
        self.label_4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4_2.setObjectName("label_4_2")
        self.gridLayout_5.addWidget(self.label_4_2, 0, 0, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(410, 390, 151, 41))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_5_2 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_5_2.setStyleSheet("font: 12pt \"楷体\";")
        self.label_5_2.setText("")
        self.label_5_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5_2.setObjectName("label_5_2")
        self.gridLayout_7.addWidget(self.label_5_2, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(570, 190, 110, 41))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_1_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_1_3.setStyleSheet("font: 12pt \"楷体\";")
        self.label_1_3.setText("")
        self.label_1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_3.setObjectName("label_1_3")
        self.gridLayout_2.addWidget(self.label_1_3, 0, 0, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(570, 240, 110, 41))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_2_3 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2_3.setFont(font)
        self.label_2_3.setStyleSheet("font: 12pt \"楷体\";")
        self.label_2_3.setText("")
        self.label_2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2_3.setObjectName("label_2_3")
        self.gridLayout_8.addWidget(self.label_2_3, 0, 0, 1, 1)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(570, 290, 110, 41))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_3_3 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_3_3.setStyleSheet("font: 12pt \"楷体\";")
        self.label_3_3.setText("")
        self.label_3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3_3.setObjectName("label_3_3")
        self.gridLayout_9.addWidget(self.label_3_3, 0, 0, 1, 1)
        self.gridLayoutWidget_10 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(570, 340, 110, 41))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_4_3 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_4_3.setStyleSheet("font: 12pt \"楷体\";")
        self.label_4_3.setText("")
        self.label_4_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4_3.setObjectName("label_4_3")
        self.gridLayout_10.addWidget(self.label_4_3, 0, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(330, 190, 110, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_1_1.setStyleSheet("font: 12pt \"楷体\";")
        self.label_1_1.setText("")
        self.label_1_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_1_1.setObjectName("label_1_1")
        self.verticalLayout.addWidget(self.label_1_1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(330, 240, 110, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2_1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2_1.setStyleSheet("font: 12pt \"楷体\";")
        self.label_2_1.setText("")
        self.label_2_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2_1.setObjectName("label_2_1")
        self.verticalLayout_2.addWidget(self.label_2_1)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(330, 290, 92, 41))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3_1 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3_1.setStyleSheet("font: 12pt \"楷体\";")
        self.label_3_1.setText("")
        self.label_3_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3_1.setObjectName("label_3_1")
        self.verticalLayout_3.addWidget(self.label_3_1)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(330, 340, 92, 41))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4_1 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_4_1.setStyleSheet("font: 12pt \"楷体\";")
        self.label_4_1.setText("")
        self.label_4_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4_1.setObjectName("label_4_1")
        self.verticalLayout_4.addWidget(self.label_4_1)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(330, 390, 92, 41))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5_1 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_5_1.setStyleSheet("font: 12pt \"楷体\";")
        self.label_5_1.setText("")
        self.label_5_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5_1.setObjectName("label_5_1")
        self.verticalLayout_5.addWidget(self.label_5_1)
        self.label_5_3 = QtWidgets.QLabel(Form)
        self.label_5_3.setGeometry(QtCore.QRect(570, 390, 108, 39))
        self.label_5_3.setStyleSheet("font: 12pt \"楷体\";")
        self.label_5_3.setText("")
        self.label_5_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5_3.setObjectName("label_5_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(390, 450, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 450, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(650, 60, 31, 28))
        self.pushButton_3.setStyleSheet("background-color: transparent;")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.preview)
        self.pushButton_2.clicked.connect(Form.next)
        self.pushButton_3.clicked.connect(Form.exit)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "上一页"))
        self.pushButton_2.setText(_translate("Form", "下一页"))
import images_rc
